# Generated by Django 3.2.18 on 2023-11-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo_cliente', models.TextField(primary_key=True, serialize=False)),
                ('apellido_paterno', models.TextField()),
                ('cuenta_bancaria', models.TextField()),
                ('direccion', models.TextField()),
                ('telefono', models.TextField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('codigo_habitacion', models.TextField(primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('precio', models.TextField()),
                ('tipo', models.TextField()),
                ('libre', models.BooleanField()),
            ],
            options={
                'db_table': 'habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialPeso',
            fields=[
                ('fecha_registro', models.DateField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
            ],
            options={
                'db_table': 'historial_peso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigo_mascota', models.TextField(primary_key=True, serialize=False)),
                ('alias', models.TextField(blank=True, null=True)),
                ('especie', models.TextField()),
                ('sexo', models.TextField()),
                ('raza', models.TextField(blank=True, null=True)),
                ('peso_actual', models.FloatField()),
                ('edad_meses', models.FloatField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('codigo_persona', models.TextField(primary_key=True, serialize=False)),
                ('nombre_persona', models.TextField()),
                ('relacion', models.TextField(blank=True, null=True)),
                ('telefono', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo_servicio', models.TextField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('precio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('tipo', models.TextField(primary_key=True, serialize=False)),
                ('fabricante', models.TextField()),
                ('precio', models.TextField()),
            ],
            options={
                'db_table': 'vacuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalendarioVacunas',
            fields=[
                ('codigo_mascota', models.OneToOneField(db_column='codigo_mascota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion_veterinaria.mascota')),
                ('fecha_vacunacion', models.DateField()),
                ('fabricante', models.TextField()),
            ],
            options={
                'db_table': 'calendario_vacunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('codigo_cliente', models.OneToOneField(db_column='codigo_cliente', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion_veterinaria.cliente')),
            ],
            options={
                'db_table': 'encargado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('codigo_mascota', models.OneToOneField(db_column='codigo_mascota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion_veterinaria.mascota')),
                ('fecha_registro', models.DateField()),
                ('dias_estadia', models.FloatField()),
                ('fecha_fin', models.DateField()),
                ('precio_total', models.TextField()),
            ],
            options={
                'db_table': 'estadia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('codigo_mascota', models.OneToOneField(db_column='codigo_mascota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion_veterinaria.mascota')),
                ('fecha_consulta', models.DateField()),
                ('enfermedad', models.TextField()),
                ('detalle_diagnostico', models.TextField()),
                ('fecha_enfermedad', models.DateField(blank=True, null=True)),
                ('detalle_tratamiento', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial_medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('codigo_mascota', models.OneToOneField(db_column='codigo_mascota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion_veterinaria.estadia')),
                ('codigo_habitacion', models.TextField()),
                ('fecha_registro', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'requerimiento',
                'managed': False,
            },
        ),
    ]
