# Generated by Django 4.2.4 on 2023-11-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_veterinaria', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioVacuna',
            fields=[
                ('fecha_vacunacion', models.DateField()),
                ('codigo_mascota', models.OneToOneField(db_column='codigo_mascota', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='administracion_veterinaria.mascota')),
                ('fabricante', models.TextField()),
            ],
            options={
                'db_table': 'calendario_vacuna',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CalendarioVacunas',
        ),
    ]
