# Generated by Django 4.2.7 on 2023-11-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_veterinaria', '0004_calendariovacuna_delete_calendariovacunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioTest',
            fields=[
                ('codigo_test', models.TextField(primary_key=True, serialize=False)),
                ('precio', models.FloatField()),
            ],
        ),
    ]
