# Generated by Django 4.2.7 on 2023-11-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_veterinaria', '0006_preciotest_precio_currency_alter_preciotest_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioTest',
        ),
    ]
