# Generated by Django 4.2.7 on 2023-11-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_veterinaria', '0010_doubleprimarykeytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoublePrimaryKeyTest',
        ),
    ]
