# Generated by Django 4.2.7 on 2023-11-26 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_veterinaria', '0008_preciotest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrecioTest',
        ),
    ]
