# Generated by Django 4.2.7 on 2023-11-26 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_veterinaria', '0009_delete_preciotest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublePrimaryKeyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(default=datetime.date.today)),
                ('codigo_consulta', models.CharField(max_length=5)),
            ],
            options={
                'unique_together': {('fecha_consulta', 'codigo_consulta')},
            },
        ),
    ]
